variables:
  - name: regionLookup
    value: |
      {
        "scus": "southcentralus",
        "cus": "centralus",
        "eus2": "eastus2"
      }

jobs:
  - job: ExampleJob
    steps:
      - script: |
          echo "The long name for region 'scus' is $REGION_LOOKUP.scus"
          echo "The long name for region 'cus' is $REGION_LOOKUP.cus"
          echo "The long name for region 'eus2' is $REGION_LOOKUP.eus2"
