# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  repositories:
    - repository: templates
      endpoint: AnotherRedbeard
      type: github
      name: AnotherRedbeard/TheOneYamlAzDO

#jobs:
#- template: common.yml@templates  # Template reference

stages:
- stage: build_stage
  displayName: 'build stage'
  jobs:
  - job: build
    displayName: 'build app service job'
    pool:
      vmImage: ubuntu-latest

    steps:
    - template: tasks/hello-world.yaml@templates
      parameters:
        command: 'this is the command'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

- stage: deploy_stage_dev
  displayName: 'Deploy to dev'
  jobs:
    - deployment: deploy_dev
      displayName: 'Deploy to dev'
      pool:
        vmImage: ubuntu-latest
      environment: dev
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo Hi dev!

- stage: deploy_stage_test
  displayName: 'Deploy to test'
  jobs:
    - deployment: deploy_test
      displayName: 'Deploy to test'
      pool:
        vmImage: ubuntu-latest
      environment: test
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo Hi test!
