# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  repositories:
    - repository: templates
      endpoint: AnotherRedbeard
      type: github
      name: AnotherRedbeard/TheOneYamlAzDO

#jobs:
#- template: common.yml@templates  # Template reference

stages:
- stage: 'Build-Stage'
  jobs:
  - job: 'Build-app-service'
    pool:
      vmImage: ubuntu-latest

    steps:
    - template: tasks/hello-world.yaml@templates
      parameters:
        command: 'this is the command'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
  - deployment: 'Deploy-to-Dev'
    pool:
      vmImage: ubuntu-latest
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo Hi!
