# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

name: Build and Deploy Todo App Service

variables:
  azureServiceConnection: 'AppServiceDeploymentDemo'
  azureContainerRegistryConnection: 'AppServiceDeploymentDemoACR'
  resourceGroupName: 'red-scus-appservicedemo-dev'
  location: 'southcentralus'
  templateFile: 'main.bicep'
  appServicePostfix: 'todoapict'
  appServiceSKU: 'B1'
  containerRegistryName: 'redscuspublicctreg01'
  containerImageName: 'todo-ct-api'
  fullImageName: '${{ variables.containerRegistryName }}.azurecr.io/${{ variables.containerImageName }}'

resources:
  repositories:
    - repository: templates
      endpoint: AnotherRedbeard
      type: github
      name: AnotherRedbeard/TheOneYamlAzDO

#jobs:
#- template: common.yml@templates  # Template reference

stages:
- stage: build_infra_stage
  displayName: 'build infrastructor stage'
  jobs:
  - job: build
    displayName: 'build infrastructor for app service job'
    pool:
      vmImage: ubuntu-latest

    steps:
    - checkout: self
    
    - template: tasks/hello-world.yaml@templates
      parameters:
        command: 'this is the command'

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        useGlobalConfig: false
        inlineScript: |
          az --version
          az group create -l ${{ variables.location }} -n ${{ variables.resourceGroupName}}
          az deployment group create --resource-group ${{ variables.resourceGroupName }} \
          --template-file ./iac/main-deploy-app-service.bicep \
          --parameters app_service_postfix=${{ variables.appServicePostfix }} app_service_sku=${{ variables.appServiceSKU }}

- stage: build_app_container
  displayName: 'build app service container stage'
  jobs:
  - job: build
    displayName: 'build app service container job'
    pool:
      vmImage: ubuntu-latest

    steps:
    - checkout: self
    
    - task: Docker@2
      displayName: Build and Push image
      inputs:
        containerRegistry: ${{ variables.azureContainerRegistryConnection }}
        repository: ${{ variables.containerImageName }}
        command: buildAndPush
        Dockerfile: $(Build.SourcesDirectory)/src/Dockerfile
        tags: |
          '${{ variables.version }}.$(Build.BuildNumber)'
          latest

- stage: deploy_stage_dev
  displayName: 'Deploy to dev'
  jobs:
    - deployment: deploy_dev
      displayName: 'Deploy to dev'
      pool:
        vmImage: ubuntu-latest
      environment: dev
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureCLI@2
                displayName: Get Container Registry Credentials
                inputs:
                  azureSubscription: ${{ variables.azureServiceConnection }}
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                    echo "##vso[task.setvariable issecret=true;variable=ACR_USERNAME]$(az acr credential show -n ${{ variables.containerRegistryName }} --query username --out tsv)"
                    echo "##vso[task.setvariable issecret=true;variable=ACR_PASSWORD]$(az acr credential show -n ${{ variables.containerRegistryName }} --query passwords[0].value --out tsv)"

              - script: echo Hi dev!

- stage: deploy_stage_test
  displayName: 'Deploy to test'
  jobs:
    - deployment: deploy_test
      displayName: 'Deploy to test'
      pool:
        vmImage: ubuntu-latest
      environment: test
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo Hi test!
