# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: AnotherRedbeard/TheOneYamlAzDO

#jobs:
#- template: common.yml@templates  # Template referenc

pool:
  vmImage: ubuntu-latest

steps:
- template: tasks/hello-world.yaml
  parameters:
    command: 'this is the command'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
